### ISSUE TITLE
Share why mock in unit testing is important

### ISSUE THREAD

**Issue by thomastthai** [sonalys/fake#2]
More experienced developers will know what mocking is. However, newer ones may not know. Perhaps you can have a paragraph or two near the beginning of the README.md file to explain the reason why people may want to use unit testing and mocking (versus fake or stub) and/or link a additional resource that explains it in more detail. When people understand the whys behind something, they are more likely to buy-in.

**Comment by sonalys** [comment]
I think that's a nice idea, to maybe put some link in the README when mentioning the Mock word for the first time, like:

> Fake is a Type-Safe [Mock](https://en.wikipedia.org/wiki/Mock_object) generator.

Do you want to do it? otherwise I can do it as well
